version: '3.2'
services:
  tests:
    depends_on:
      - kafka-tests
      - influxdb-tests
    image: jticker/aggregator-tests
    build:
      context: .
      dockerfile: Dockerfile.tests
    stdin_open: true
    tty: true
    volumes:
      - './:/app'
    environment:
      INFLUX_HOST: influxdb-tests
      KAFKA_BOOTSTRAP_SERVERS: "kafka-tests:9092"
      METADATA_URL: "http://jassets:8000/"
    networks:
      - jassets_default
      - default
  influxdb-tests:
    image: influxdb:1.7-alpine
    environment:
      INFLUXDB_DB: jticker_tests  # create test database
  kafka-tests:
    image: jibrelnetwork/kafka
    depends_on:
      - zookeeper-tests
    environment:
      BROKERID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-tests:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-tests:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_CLEANUP_POLICY: compact
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper-tests:
    image: zookeeper
    restart: always
networks:
  jassets_default:
    external: true

