FROM jticker/aggregator

USER root

COPY --chown=app:app . /app/

RUN pip install --no-cache-dir -e /app/jticker-core
RUN pip install --no-cache-dir -e /app/[dev]

USER app

ENTRYPOINT ["/app/run.sh"]

CMD ["test"]
